name = "JuliaGLM"
uuid = "d62f3426-b328-4065-b1cd-fa40c3c5e4f7"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

#[compat]
#LinearAlgebra = "1.11.0"
#StaticArrays = "1.9.14"
